#!/usr/bin/env bash

# batch-add static BM TGs script - W0CHP
# expects args passed from bm_manager.php

cat /var/www/dashboard/.bm_tgs.batch |
while IFS=$'\n' read -r talkgroup; do
    curl -s \
        --user "$1:" \
        --data "talkgroup=$talkgroup&timeslot=$3" \
        "https://api.brandmeister.network/v1.0/repeater/talkgroup/?action=ADD&id=$2" ; \
done
echo -e "All Requested Static Talk Groups Added!\n"

# delete unused file
mount -o remount,rw /
rm -f /var/www/dashboard/.bm_tgs.batch
sync
mount -o remount,ro /

exit 0
